# Generated by Django 5.2.11 on 2026-02-13 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الثلاثي"),
                ),
                (
                    "student_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="جوال الطالب"
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(max_length=15, verbose_name="جوال ولي الأمر"),
                ),
                (
                    "identity_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="رقم الهوية"
                    ),
                ),
                (
                    "parent_identity",
                    models.CharField(max_length=10, verbose_name="رقم هوية ولي الأمر"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1_pri", "أولى ابتدائي"),
                            ("2_pri", "ثانية ابتدائي"),
                            ("3_pri", "ثالثة ابتدائي"),
                            ("4_pri", "رابعة ابتدائي"),
                            ("5_pri", "خامسة ابتدائي"),
                            ("6_pri", "سادسة ابتدائي"),
                            ("1_med", "أول متوسط"),
                            ("2_med", "ثاني متوسط"),
                            ("3_med", "ثالث متوسط"),
                            ("1_sec", "أول ثانوي"),
                            ("2_sec", "ثاني ثانوي"),
                            ("3_sec", "ثالث ثانوي"),
                            ("uni", "جامعي"),
                        ],
                        max_length=20,
                        verbose_name="الصف الدراسي",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "last_tested_part",
                    models.CharField(max_length=50, verbose_name="آخر جزء تم اختباره"),
                ),
                (
                    "previous_center",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="التحفيظ السابق",
                    ),
                ),
                ("neighborhood", models.CharField(max_length=100, verbose_name="الحي")),
                (
                    "status",
                    models.CharField(
                        choices=[("منتظر", "منتظر"), ("منتظم", "منتظم")],
                        default="منتظر",
                        max_length=20,
                    ),
                ),
                ("educational_stage", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعلم المسؤول",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("حاضر", "حاضر"),
                            ("غائب", "غائب"),
                            ("مستأذن", "مستأذن"),
                        ],
                        default="حاضر",
                        max_length=10,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quran_center.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "date")},
            },
        ),
    ]
