# Generated by Django 5.2.11 on 2026-02-13 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StageSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_approve_students",
                    models.BooleanField(default=True, verbose_name="يمكنه قبول الطلاب"),
                ),
                (
                    "can_assign_teachers",
                    models.BooleanField(
                        default=True, verbose_name="يمكنه تعيين المعلمين"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_supervisor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشرف مرحلة",
                "verbose_name_plural": "مشرفو المراحل",
            },
        ),
    ]
