# Generated by Django 5.2.11 on 2026-02-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0005_roles_and_exam_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date"],
                "verbose_name": "حضور",
                "verbose_name_plural": "سجلات الحضور",
            },
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quran_center.student",
                verbose_name="الطالب",
            ),
        ),
        migrations.AlterField(
            model_name="examnomination",
            name="internal_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="درجة الاختبار الداخلي",
            ),
        ),
        migrations.AlterField(
            model_name="examnomination",
            name="teacher_grade",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="درجة المعلم",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AlterField(
            model_name="student",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="الحي"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_identity",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="رقم هوية ولي الأمر"
            ),
        ),
    ]
