# Generated by Django 5.2.11 on 2026-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quran_center",
            "0006_alter_attendance_options_alter_attendance_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="الاسم الثلاثي"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1_pri", "أول ابتدائي"),
                    ("2_pri", "ثاني ابتدائي"),
                    ("3_pri", "ثالث ابتدائي"),
                    ("4_pri", "رابع ابتدائي"),
                    ("5_pri", "خامس ابتدائي"),
                    ("6_pri", "سادس ابتدائي"),
                    ("1_med", "أول متوسط"),
                    ("2_med", "ثاني متوسط"),
                    ("3_med", "ثالث متوسط"),
                    ("1_sec", "أول ثانوي"),
                    ("2_sec", "ثاني ثانوي"),
                    ("3_sec", "ثالث ثانوي"),
                    ("uni", "جامعي"),
                ],
                default="",
                max_length=20,
                verbose_name="الصف الدراسي",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                blank=True, default="", max_length=15, verbose_name="جوال ولي الأمر"
            ),
        ),
    ]
