# Generated by Django 5.2.11 on 2026-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0007_alter_student_full_name_alter_student_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="identity_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="رقم الهوية"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_identity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رقم هوية ولي الأمر"
            ),
        ),
    ]
