# Generated by Django 5.2.11 on 2026-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0008_alter_student_identity_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="identity_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="رقم الهوية"
            ),
        ),
    ]
