# Generated by Django 5.2.11 on 2026-02-14 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0009_alter_student_identity_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("الأحد", "الأحد"),
                            ("الاثنين", "الاثنين"),
                            ("الثلاثاء", "الثلاثاء"),
                            ("الأربعاء", "الأربعاء"),
                            ("الخميس", "الخميس"),
                        ],
                        max_length=10,
                        verbose_name="اليوم",
                    ),
                ),
                ("week_number", models.IntegerField(verbose_name="رقم الأسبوع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("حاضر", "حاضر"),
                            ("غائب", "غائب"),
                            ("مستأذن", "مستأذن"),
                            ("متأخر", "متأخر"),
                        ],
                        default="حاضر",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور معلم",
                "verbose_name_plural": "سجلات حضور المعلمين",
                "ordering": ["-date"],
                "unique_together": {("teacher", "date")},
            },
        ),
    ]
