# Generated by Django 5.2.11 on 2026-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0010_teacherattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="jamiaa_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="رقم الجمعية"
            ),
        ),
    ]
