# Generated by Django 5.2.11 on 2026-04-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_center', '0014_convert_student_unique_id_to_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPlanPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_plan', models.CharField(choices=[('2', 'صفحتان'), ('1', 'صفحة'), ('0.5', 'نصف صفحة'), ('0.25', 'ربع صفحة')], default='1', max_length=10, verbose_name='نوع الحفظ الافتراضي')),
                ('big_review_pages', models.PositiveIntegerField(default=5, verbose_name='عدد صفحات المراجعة الكبرى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_preference', to=settings.AUTH_USER_MODEL, verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'تفضيل خطة المعلم',
                'verbose_name_plural': 'تفضيلات خطط المعلمين',
            },
        ),
    ]
