# Generated by Django 5.2.11 on 2026-04-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0015_teacherplanpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="تاريخ الميلاد"
            ),
        ),
    ]
