# Generated by Django 5.2.11 on 2026-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0018_smstemplatesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("حاضر", "حاضر"),
                    ("غائب", "غائب"),
                    ("غياب بعذر", "غياب بعذر"),
                    ("مستأذن", "منصرف"),
                    ("متأخر", "متأخر"),
                ],
                default="حاضر",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="teacherattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("حاضر", "حاضر"),
                    ("غائب", "غائب"),
                    ("غياب بعذر", "غياب بعذر"),
                    ("مستأذن", "منصرف"),
                    ("متأخر", "متأخر"),
                ],
                default="حاضر",
                max_length=10,
                verbose_name="الحالة",
            ),
        ),
    ]
