# Generated by Django 5.2.11 on 2026-04-24 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quran_center", "0019_alter_attendance_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemorizationTemplateBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="قوالب حفظ مخصصة",
                        max_length=120,
                        verbose_name="اسم الحزمة",
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="اسم الملف المرفوع",
                    ),
                ),
                (
                    "template_definitions",
                    models.JSONField(default=list, verbose_name="تعريفات القوالب"),
                ),
                (
                    "memorization_data",
                    models.JSONField(default=dict, verbose_name="بيانات الحفظ"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="الحزمة النشطة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_memorization_bundles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تم الرفع بواسطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حزمة قوالب الحفظ",
                "verbose_name_plural": "حزم قوالب الحفظ",
                "ordering": ["-created_at"],
            },
        ),
    ]
