# Generated by Django 5.2.6 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_center', '0020_memorizationtemplatebundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplatesetting',
            name='section',
            field=models.CharField(
                choices=[
                    ('absent', 'غياب'),
                    ('absent_excused', 'غياب بعذر'),
                    ('late', 'تأخر'),
                    ('excused', 'انصراف'),
                    ('association_exam', 'اختبار الجمعية'),
                ],
                max_length=20,
                verbose_name='القسم',
            ),
        ),
    ]
