# Generated by Django 5.2.11 on 2026-04-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran_center', '0021_alter_smstemplatesetting_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examnomination',
            name='exam_halaqa_teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='association_exam_halaqa_nominations',
                to=settings.AUTH_USER_MODEL,
                verbose_name='اسم حلقة الاختبار',
            ),
        ),
    ]
