# Generated by Django 5.2.11 on 2026-04-25 00:00

from django.db import migrations, models


def add_missing_teacherprofile_columns(apps, schema_editor):
    table_name = 'quran_center_teacherprofile'
    qn = schema_editor.quote_name

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'class_name' not in existing_columns:
        schema_editor.execute(
            f"ALTER TABLE {qn(table_name)} ADD COLUMN {qn('class_name')} varchar(120) NULL"
        )

    if 'halaqa_name' not in existing_columns:
        schema_editor.execute(
            f"ALTER TABLE {qn(table_name)} ADD COLUMN {qn('halaqa_name')} varchar(120) NULL"
        )


def noop_reverse(apps, schema_editor):
    # Keep reverse as no-op to avoid destructive column drops.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quran_center', '0022_examnomination_exam_halaqa_teacher'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_teacherprofile_columns, noop_reverse),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='teacherprofile',
                    name='class_name',
                    field=models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name='اسم الحلقة',
                    ),
                ),
                migrations.AddField(
                    model_name='teacherprofile',
                    name='halaqa_name',
                    field=models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name='اسم الحلقة (بديل)',
                    ),
                ),
            ],
        ),
    ]
